version: '3.1'

services:
  db:
    image: postgres:11.2
    restart: always
    container_name: scanner-doc
    environment:
      POSTGRES_USER: dmitrijmilutin
      POSTGRES_DB: scanner-postgres
      POSTGRES_PASSWORD: example
    volumes:
      - ../db:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
      # - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5433:5433